# -*- coding: utf-8 -*-
"""AI_CopyForge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abd5aYK8NwJsFHJb6HW-kqE3sTprTEcE

# ════════════════════════════════════════════════════════════
# ✍️  PROJECT 2 — AUTOMATED COPYWRITING & TONE TRANSFORMER
# ═════════════════════════════════════════════════
#  Internship  : Decode Labs — Generative AI Industrial Training Kit
#  Developer   : Taj Wali Khan
#  Platform    : Google Colab
#  LLM Provider: Groq — genuinely free tier, no credit card required
#  Model       : llama-3.3-70b-versatile (stable, production model)
#
#  GOAL (from the official brief):
#  Build a system that takes a raw product description and automatically
#  generates professional marketing copy, tailored to different
#  platforms, using dynamic prompt templates and tunable Temperature /
#  Top_P parameters.
#
#  ── A NOTE ON "COMPLETELY FREE TECHNOLOGIES" ────────────────────────
#  The official blueprint references OpenAI (gpt-4, gpt-4o, o1) and the
#  paid OpenAI Batch API. Those cost real money per token. Since this
#  build must use completely free technology, we use Groq instead —
#  same style of Chat Completions API, genuinely free to use, and
#  already proven working in your Project 1 chatbot. Where the
#  blueprint calls for OpenAI's paid Batch API, we build the same
#  *outcome* (processing many products efficiently) using Python's
#  free, built-in `asyncio` + `Semaphore` pattern instead.
"""

from google.colab import drive

drive.mount('/content/drive')

import os

print(os.path.exists("/content/drive"))

import os

project_path = "/content/drive/MyDrive/AI_CopyForge"

os.makedirs(project_path, exist_ok=True)

print("✅ Project folder created!")
print(project_path)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/AI_CopyForge

import os

print(os.getcwd())



import os

folders = [
    "assets",
    "screenshots",
    ".streamlit"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("✅ Folders created successfully!")

files = [
    "app.py",
    "ai_engine.py",
    "prompt_templates.py",
    "utils.py",
    "requirements.txt",
    "README.md",
    ".env",
    ".env.example",
    ".gitignore"
]

for file in files:
    with open(file, "w") as f:
        pass

print("✅ Files created successfully!")

import os

print("📂 Project Structure:\n")

for item in sorted(os.listdir()):
    print(item)

!pip install -q streamlit groq python-dotenv

import streamlit
from groq import Groq
from dotenv import load_dotenv

print("✅ All libraries installed successfully!")

requirements = """streamlit>=1.45.0
groq>=0.30.0
python-dotenv>=1.0.1
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("✅ requirements.txt created!")

env_example = """GROQ_API_KEY=your_api_key_here"""

with open(".env.example", "w") as f:
    f.write(env_example)

print("✅ .env.example created!")

gitignore = """.env
__pycache__/
*.pyc
.venv/
venv/
.streamlit/secrets.toml
"""

with open(".gitignore", "w") as f:
    f.write(gitignore)

print("✅ .gitignore created!")

api_key = input("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 ")

with open(".env", "w") as f:
    f.write(f"GROQ_API_KEY={api_key}")

print("✅ API key saved successfully!")

import getpass

# Securely prompt for the API key
new_key = getpass.getpass('Paste your Groq API key here: ')

if new_key.startswith('gsk_'):
    with open('.env', 'w') as f:
        f.write(f'GROQ_API_KEY={new_key}')
    print('✅ .env file updated with the new API key!')
else:
    print('❌ Invalid format. Groq keys usually start with gsk_')

# Reload the environment variables and re-initialize the client
load_dotenv(override=True)
api_key = os.getenv('GROQ_API_KEY')
client = Groq(api_key=api_key)

print('✅ Groq client re-initialized with the new key.')

import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("GROQ_API_KEY")

if api_key:
    print("✅ API Key Loaded Successfully!")
    print("Key Preview:", api_key[:10] + "...")
else:
    print("❌ API Key Not Found!")

import os

print("=" * 50)
print("🚀 AI CopyForge - Project Setup Complete")
print("=" * 50)

print("\n📁 Files:")
for item in sorted(os.listdir()):
    print("✔", item)

print("\n✅ Phase 1 Completed Successfully!")

product_name = "Smart AI Watch"

product_description = """
A smartwatch that tracks health, heart rate,
sleep quality, and fitness activities.
"""

platform = "LinkedIn"

tone = "Professional"

target_audience = "Business Professionals"

print("✅ Sample Inputs Created")

print("Product Name :", product_name)
print("Platform     :", platform)
print("Tone         :", tone)
print("Audience     :", target_audience)

prompt = f"""
You are an expert copywriter.

Write a {tone} marketing post for {platform}.

Product Name:
{product_name}

Product Description:
{product_description}

Target Audience:
{target_audience}

Requirements:
- Keep it engaging
- Add a strong call to action
- Use emojis where appropriate
- Keep it professional
"""

print(prompt)

def build_prompt(
    product_name,
    product_description,
    platform,
    tone,
    target_audience,
):
    prompt = f"""
You are an expert AI marketing copywriter.

Write a {tone} marketing post for {platform}.

Product Name:
{product_name}

Product Description:
{product_description}

Target Audience:
{target_audience}

Requirements:
- Professional writing
- Clear and engaging
- Include a call to action
- Add suitable emojis
"""
    return prompt

my_prompt = build_prompt(
    product_name,
    product_description,
    platform,
    tone,
    target_audience,
)

print(my_prompt)

creativity = "High"

word_limit = 120

language = "English"

print("✅ Additional Settings Ready")

def build_prompt(
    product_name,
    product_description,
    platform,
    tone,
    target_audience,
    creativity,
    word_limit,
    language,
):
    prompt = f"""
You are an expert AI copywriter.

Create a {tone} marketing copy.

Platform:
{platform}

Language:
{language}

Target Audience:
{target_audience}

Creativity Level:
{creativity}

Maximum Words:
{word_limit}

Product Name:
{product_name}

Product Description:
{product_description}

Requirements:
- Start with an attention-grabbing hook.
- Highlight the product's benefits.
- Keep the tone consistent.
- End with a clear call to action.
- Do not exceed the word limit.
"""

    return prompt

prompt = build_prompt(
    product_name,
    product_description,
    platform,
    tone,
    target_audience,
    creativity,
    word_limit,
    language,
)

print(prompt)

prompt = build_prompt(
    product_name,
    product_description,
    platform,
    tone,
    target_audience,
    creativity,
    word_limit,
    language,
)

print(prompt)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile prompt_templates.py
# 
# def build_prompt(
#     product_name,
#     product_description,
#     platform,
#     tone,
#     target_audience,
#     creativity,
#     word_limit,
#     language,
# ):
#     return f"""
# You are an expert AI copywriter.
# 
# Create a {tone} marketing copy.
# 
# Platform:
# {platform}
# 
# Language:
# {language}
# 
# Target Audience:
# {target_audience}
# 
# Creativity Level:
# {creativity}
# 
# Maximum Words:
# {word_limit}
# 
# Product Name:
# {product_name}
# 
# Product Description:
# {product_description}
# 
# Requirements:
# - Start with an attention-grabbing hook.
# - Highlight key benefits.
# - Maintain the requested tone.
# - Include a clear call to action.
# - Stay within the word limit.
# """

from prompt_templates import build_prompt

prompt = build_prompt(
    "AI Laptop",
    "A lightweight AI-powered laptop for developers.",
    "LinkedIn",
    "Professional",
    "Software Engineers",
    "High",
    150,
    "English",
)

print(prompt)

from groq import Groq
from dotenv import load_dotenv
import os

print("✅ Libraries Imported Successfully")

load_dotenv()

api_key = os.getenv("GROQ_API_KEY")

if api_key:
    print("✅ API Key Loaded Successfully")
    print("Preview:", api_key[:10] + "...")
else:
    print("❌ API Key Not Found")

client = Groq(api_key=api_key)

print("✅ Groq Client Created Successfully")

try:
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": "Say hello in one sentence."
            }
        ]
    )
    print("Groq Response:", response.choices[0].message.content)
except Exception as e:
    print(f"❌ Error: {e}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ai_engine.py
# import os
# from groq import Groq
# from dotenv import load_dotenv
# from prompt_templates import build_prompt
# 
# load_dotenv()
# 
# class AIEngine:
#     def __init__(self):
#         self.api_key = os.getenv("GROQ_API_KEY")
#         if not self.api_key:
#             raise ValueError("❌ GROQ_API_KEY not found in environment variables.")
#         self.client = Groq(api_key=self.api_key)
# 
#     def generate_copy(self, product_name, product_description, platform, tone, target_audience, creativity, word_limit, language):
#         # 1. Build the prompt using the template
#         prompt = build_prompt(
#             product_name, product_description, platform, tone,
#             target_audience, creativity, word_limit, language
#         )
# 
#         # 2. Call the Groq API
#         try:
#             response = self.client.chat.completions.create(
#                 model="llama-3.3-70b-versatile",
#                 messages=[
#                     {"role": "system", "content": "You are a professional marketing copywriter."},
#                     {"role": "user", "content": prompt}
#                 ],
#                 temperature=0.7 if creativity == "Medium" else (1.0 if creativity == "High" else 0.3),
#                 max_tokens=word_limit * 2 # Buffer for response tokens
#             )
#             return response.choices[0].message.content
#         except Exception as e:
#             return f"❌ Error generating copy: {str(e)}"

from ai_engine import AIEngine

# Initialize the engine
engine = AIEngine()

# Test with our sample data
copy_result = engine.generate_copy(
    product_name=product_name,
    product_description=product_description,
    platform=platform,
    tone=tone,
    target_audience=target_audience,
    creativity=creativity,
    word_limit=word_limit,
    language=language
)

print("🚀 Generated Marketing Copy:\n")
print(copy_result)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from ai_engine import AIEngine
# 
# # Page Config
# st.set_page_config(page_title="AI CopyForge", page_icon="🚀")
# 
# # Initialize AI Engine
# @st.cache_resource
# def get_engine():
#     return AIEngine()
# 
# try:
#     engine = get_engine()
# except Exception as e:
#     st.error(f"Initialization Error: {e}")
#     st.stop()
# 
# # Sidebar - Settings
# st.sidebar.title("⚙️ Settings")
# platform = st.sidebar.selectbox("Platform", ["LinkedIn", "Instagram", "Twitter", "Facebook", "Email"])
# tone = st.sidebar.selectbox("Tone", ["Professional", "Casual", "Persuasive", "Witty", "Urgent"])
# creativity = st.sidebar.select_slider("Creativity", options=["Low", "Medium", "High"], value="Medium")
# word_limit = st.sidebar.number_input("Word Limit", min_value=10, max_value=500, value=150)
# language = st.sidebar.selectbox("Language", ["English", "Spanish", "French", "German", "Portuguese"])
# 
# # Main UI
# st.title("🚀 AI CopyForge")
# st.subheader("Generate High-Converting Marketing Copy")
# 
# with st.form("copy_form"):
#     product_name = st.text_input("Product Name", placeholder="e.g., Smart AI Watch")
#     target_audience = st.text_input("Target Audience", placeholder="e.g., Business Professionals")
#     product_description = st.text_area("Product Description", placeholder="Describe key features and benefits...")
# 
#     submit = st.form_submit_button("Generate Copy")
# 
# if submit:
#     if not product_name or not product_description:
#         st.warning("Please provide both a product name and description.")
#     else:
#         with st.spinner("✍️ Crafting your copy..."):
#             result = engine.generate_copy(
#                 product_name, product_description, platform,
#                 tone, target_audience, creativity, word_limit, language
#             )
# 
#             st.divider()
#             st.subheader("✨ Your Generated Copy")
#             st.write(result)
#             st.button("📋 Copy to Clipboard", on_click=lambda: st.write("Feature coming soon!"))

print("✅ app.py has been created with the Streamlit interface!")
print("Next, we can look into how to run this on Google Colab using Localtunnel or Ngrok.")

!npm install -g localtunnel

import subprocess
import threading
import time

def run_streamlit():
    subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

# Start Streamlit in a separate thread
thread = threading.Thread(target=run_streamlit)
thread.start()

# Wait for the server to start
time.sleep(5)

# Get the public IP (needed for Localtunnel password)
print("Your Tunnel Password (Public IP):", subprocess.getoutput("curl ipv4.icanhazip.com"))

# Expose the port
!npx localtunnel --port 8501

!npm install -g localtunnel

import subprocess
import threading
import time

def run_streamlit():
    subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

# Start Streamlit in a separate thread
thread = threading.Thread(target=run_streamlit)
thread.start()

# Wait for the server to start
time.sleep(5)

# Get the public IP (needed for Localtunnel password)
print("Your Tunnel Password (Public IP):", subprocess.getoutput("curl ipv4.icanhazip.com"))

# Expose the port
!npx localtunnel --port 8501

!npm install -g localtunnel

import subprocess
import threading
import time

def run_streamlit():
    subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

# Start Streamlit in a separate thread
thread = threading.Thread(target=run_streamlit)
thread.start()

# Wait for the server to start
time.sleep(5)

# Get the public IP (needed for Localtunnel password)
print("Your Tunnel Password (Public IP):", subprocess.getoutput("curl ipv4.icanhazip.com"))

# Expose the port
!npx localtunnel --port 8501

!npm install -g localtunnel

import subprocess
import threading
import time
import socket

def run_streamlit():
    subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

# Start Streamlit in a separate thread
thread = threading.Thread(target=run_streamlit)
thread.start()

# Wait for the server to start
time.sleep(5)

# Get the public IP (needed for Localtunnel password)
print("Your Tunnel Password (Public IP):", subprocess.getoutput("curl ipv4.icanhazip.com"))

# Expose the port
!npx localtunnel --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from ai_engine import AIEngine
# 
# # Page Config
# st.set_page_config(page_title="AI CopyForge", page_icon="🚀")
# 
# # Initialize AI Engine
# @st.cache_resource
# def get_engine():
#     return AIEngine()
# 
# try:
#     engine = get_engine()
# except Exception as e:
#     st.error(f"Initialization Error: {e}")
#     st.stop()
# 
# # Sidebar - Settings
# st.sidebar.title("⚙️ Settings")
# platform = st.sidebar.selectbox("Platform", ["LinkedIn", "Instagram", "Twitter", "Facebook", "Email"])
# tone = st.sidebar.selectbox("Tone", ["Professional", "Casual", "Persuasive", "Witty", "Urgent"])
# creativity = st.sidebar.select_slider("Creativity", options=["Low", "Medium", "High"], value="Medium")
# word_limit = st.sidebar.number_input("Word Limit", min_value=10, max_value=500, value=150)
# language = st.sidebar.selectbox("Language", ["English", "Spanish", "French", "German", "Portuguese"])
# 
# # Main UI
# st.title("🚀 AI CopyForge")
# st.subheader("Generate High-Converting Marketing Copy")
# 
# with st.form("copy_form"):
#     product_name = st.text_input("Product Name", placeholder="e.g., Smart AI Watch")
#     target_audience = st.text_input("Target Audience", placeholder="e.g., Business Professionals")
#     product_description = st.text_area("Product Description", placeholder="Describe key features and benefits...")
# 
#     submit = st.form_submit_button("Generate Copy")
# 
# if submit:
#     if not product_name or not product_description:
#         st.warning("Please provide both a product name and description.")
#     else:
#         with st.spinner("✍️ Crafting your copy..."):
#             result = engine.generate_copy(
#                 product_name, product_description, platform,
#                 tone, target_audience, creativity, word_limit, language
#             )
# 
#             st.divider()
#             st.subheader("✨ Your Generated Copy")
#             st.write(result)
#             st.button("📋 Copy to Clipboard", on_click=lambda: st.write("Feature coming soon!"))

print("✅ app.py has been created with the Streamlit interface!")
print("Next, we can look into how to run this on Google Colab using Localtunnel or Ngrok.")